define( 
({
"export":"Export",
"refresh":"Refresh",
"apply":"Apply",
"no":"No",
"loading":"loading...",
"date":"Date",
"yes":"Yes",
"close":"Close",
"path":"Path",
"used":"Used",
"forward":"Forward",
"delete":"Delete",
"untitled":"Untitled",
"volume":"Volume",
"login":"Log in",
"ok":"OK",
"up":"Up",
"chooseWall":"Choose a wallpaper",
"title":"Title",
"total":"Total",
"back":"Back",
"play":"Play",
"error":"Error",
"remove":"Remove",
"upload":"Upload",
"markAsRead":"Mark as read",
"rename":"Rename",
"open":"Open",
"isCategory":"Is Category",
"run":"Run",
"openUrl":"Open URL",
"save":"Save",
"loadOrSave":"Load/Save",
"stop":"Stop",
"name":"Name",
"icon":"Icon",
"openFile":"Open File",
"go":"Go",
"create":"Create",
"download":"Download",
"category":"Category",
"cancel":"Cancel",
"saveAs":"Save As",
"url":"URL",
"remaining":"Remaining",
"add":"Add",
"import":"Import",
"new":"New",
"metadata":"Metadata",
"pause":"Pause"
})
);
